project:
  type: website
  output-dir: _site
  resources:
    - ./resources/assets/*.png
    - ./resources/assets/*.jpg
    - ./resources/assets/favicon.ico

website:
  title: "Luca Uckermann"
  favicon: ./resources/assets/favicon.ico

format:
  revealjs: default
