---
title: "Hi there 👋🏼"
#subtitle: ""
#date: "today"
date-format: "long"
author: "Luca Uckermann"
institute: "Research Associate @TH Köln"

quarto-required: ">=1.3.0"
lang: en

theme:
  - dark

toc: true
toc-depth: 1
toc-title: "Table of contents"

number-sections: false

incremental: false
scrollable: false

format:
  revealjs:
    slide-level: 2
    navigation-mode: vertical
    slide-number: c
    controls: true
    progress: true
    touch: true
    transition: slide
    center: true
    auto-stretch: true

    width: 1050
    height: 700
    embed-resources: true
---

# 🏫 Education

## 🎓 TH Köln

- [M.Sc. Computer Science & Engineering](https://th-koeln.de/en/academics/computer-science--engineering-masters-program_106742.php) (09/2022&thinsp;&ndash;&thinsp;03/2025)
- [B.Sc. Computer Science & Engineering](https://th-koeln.de/en/academics/computer-science--engineering-bachelors-program_106741.php) (09/2018&thinsp;&ndash;&thinsp;08/2022)

## 🌍 Université Gustave Eiffel ([Double Degree](https://th-koeln.de/en/international_office/double-degree-computer-science-and-engineering-master_112507.php))

- [M.Sc. Intelligent Systems & Applications](https://formations.univ-gustave-eiffel.fr/en/our-studies/detail?tx_formations_formationslistenplugin%5Baction%5D=showEN&tx_formations_formationslistenplugin%5Bcontroller%5D=Formations&tx_formations_formationslistenplugin%5BparcoursId%5D=348&cHash=725dd68f91fcd0e768a0777f60d29e1f) (09/2024&thinsp;&ndash;&thinsp;02/2025, [Erasmus+](https://th-koeln.de/en/international_office/erasmus--studying-in-europe_88135.php) exchange)

# 💼 Work Experience

## 👨🏻‍🔬 Current Roles

- [Research Associate](https://th-koeln.de/personen/luca.uckermann/) (04/2025&thinsp;&ndash;&thinsp;present)
- [Lecturer](https://th-koeln.de/weiterbildung/ki-im-unternehmen_130040.php/) (03/2026&thinsp;&ndash;&thinsp;present)

## 👨🏻‍💻 Previous Roles

- [Research Assistant](https://th-koeln.de/personen/luca.uckermann/) (02/2025&thinsp;&ndash;&thinsp;04/2025)
- [Junior Software Developer](https://beebucket.ai/) (10/2021&thinsp;&ndash;&thinsp;01/2025)

# 📚 Publications

- [DEEP-SEED: From Scratch to Ensemble &ndash; A Deep Learning Approach to Seedling Classification](https://doi.org/10.57684/COS-1297) (06/2025)
- [Multi-Target Multi-Camera Tracking (MTMCT) and Re-Identification (re-ID) from Detection to Tracking in Real-Time Scenarios](https://doi.org/10.57683/EPUB-3015) (01/2024)

# 🤖 Projects

- [Analyzing and Visualizing Ridership Patterns in Île-de-France Rail Network](https://luckerma.shinyapps.io/DSViz_Project/)
- [Simulation for Shared Micromobility](https://luckerma.github.io/mas_project/)

# 📝 Theses

- Master's Thesis:\
  &raquo;From Detection to Association: A Real-Time Framework for Multi-Target Multi-Camera Tracking using Heterogeneous Cameras across Diverse Fields of View&laquo;
- Bachelor's Thesis:\
  &raquo;Automatisiertes Testen von Softwareartefakten auf heterogenen und ressourcenbeschränkten industriellen Edge-Devices&laquo;

# 📊 Current Projects / Research

Deep learning-based computer vision models in the following domains:

- 👁️ Ophthalmology
- 🌱 Biomass estimation
- ⛔ Traffic sign recognition

# 🔗 Links

- [luckerma.github.io](https://luckerma.github.io/)
- [github/luckerma](https://github.com/luckerma/)
- [in/luca-uckermann](https://linkedin.com/in/luca-uckermann/)
- [th-koeln/luca.uckermann](https://th-koeln.de/personen/luca.uckermann/)
- [orcid/0009-0005-2957-6331](https://orcid.org/0009-0005-2957-6331/)
- [researchgate/luca-uckermann](https://researchgate.net/profile/luca-uckermann/)
- [scholar/luca-uckermann](https://scholar.google.com/citations?user=Q0xLw-0AAAAJ)
- [mailto:luckerma@th-koeln.de](mailto:luca.uckermann@th-koeln.de)
